### ISSUE TITLE
[ERROR] Metadata inside file gif

### ISSUE THREAD

**Issue by MatteoVilardo** [gwaredd/mgGif#2]
Hello, i found an issue, the library throw an exception when is reading the file, if it contains metadata information inside. I don't know if is possibile ignore this informations or delete them during the import. 

I can't attach the gif because all my project is under NDA, but i can share a screenshot 

[METADATA BEGIN]
![image](https://user-images.githubusercontent.com/25264917/156348397-6ea68285-a736-49a6-9461-269f17ac2d24.png)

[METADATA END]
![image](https://user-images.githubusercontent.com/25264917/156348574-7ed2a887-9f94-4161-bc4d-4203c85767b0.png)

**Comment by gwaredd** [comment]
If you could create a test image with metadata but without any NDA content I'll take a look.
